## Simulation

Functions

`np.random.standard_normal`, `np.random.standard_t`, `np.random.RandomState`

### Exercise 5

Simulate 100 standard Normal random variables


In [7]:
import numpy as np
from scipy import stats

In [30]:
x = np.random.standard_normal(100)
x[:10]

array([ 0.02404725,  0.10750431,  0.45300931, -1.36431501,  0.98413083,
       -1.23968834,  0.97603543, -0.09347352,  0.27701028,  1.2583053 ])

### Exercise 6

Simulate 100 random variables from a $N\left(.08,.2^{2}\right)$

In [46]:
np.random.seed(1)
x = np.random.normal(0.08, 0.20, 100)
x[:10]

array([ 0.40486907, -0.04235128, -0.02563435, -0.13459372,  0.25308153,
       -0.38030774,  0.42896235, -0.07224138,  0.14380782,  0.03012592])

In [48]:
np.random.seed(1)
x = np.random.normal(loc = 0.08, scale = 0.20, size = 100)
x[:10]

array([ 0.40486907, -0.04235128, -0.02563435, -0.13459372,  0.25308153,
       -0.38030774,  0.42896235, -0.07224138,  0.14380782,  0.03012592])

### Exercise 8

Simulate 100 random variables from a Students t with 8 degrees of freedom with a mean of 8% and a volatility of 20%. Note: $V\left[X\right]=\frac{\nu}{\nu-2}$ when $X\sim t_{\nu}$.

In [148]:
np.random.seed(1)
rv = np.random.standard_t(df = 8, size = 100)
rv[:10]

array([ 2.0087496 , -0.94659562, -0.75224146, -1.88345664,  0.35616341,
       -0.5999975 , -0.37358462,  0.69377892, -0.23095939,  1.83790437])

In [149]:
np.mean(rv)

0.1274897527317306

In [150]:
std_rv = np.sqrt(8/(8-2))
std_rv

1.1547005383792515

In [151]:
rv_adj = (rv / std_rv)*0.2
np.std(rv_adj)

0.1796536164210192

In [153]:
x = 0.08 +rv_adj

In [154]:
np.mean(x)

0.10208187291757502

In [155]:
np.std(x)

0.1796536164210192


### Exercise 9

Simulate two identical sets of 100 standard normal random variables by resetting the random number generator.

In [174]:
np.random.seed(10)
x = np.random.standard_normal(100)

In [157]:
np.random.seed(10)
y = np.random.standard_normal(100)

In [158]:
x-y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


### Exercise 10

Repeat exercise 7 using only `standard_normal`.

In [180]:
np.random.seed(1)

In [181]:
n_draws = 1000000

In [182]:
z = np.random.standard_normal(size = n_draws)
z.shape

(1000000,)

In [183]:
z[:10]

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038])

In [184]:
df = 8
y = np.random.standard_normal((n_draws, df))
y.shape

(1000000, 8)

In [186]:
y[:,1]

array([ 1.52713406, -3.22801705, -1.14486683, ...,  1.18379197,
       -0.78083164, -0.34121801])

In [187]:
q = np.sum(y**2,1)
q.shape

(1000000,)

In [188]:
denominator = np.sqrt(q/df)
denominator

array([0.99107202, 1.46725213, 1.27429443, ..., 0.88742386, 0.59864847,
       1.12767769])

In [189]:
t = z / denominator

In [190]:
np.mean(t)

0.0009027335490841813

In [191]:
np.std(t)

1.1539012499637058

In [192]:
# theoretical vaue of the std of a student's t distribution with 8 degrees of freedom
# much closer with 1,000,000 iterations of the rv than just 100!
np.sqrt(8/(8-2))

1.1547005383792515